#!/usr/bin/env perl
use strict;
use warnings;
use utf8;

# gnu_compat: --opt="..." is allowed.
# no_bundling: single character option is not bundled.
# no_ignore_case: no ignore case on long option.
use Getopt::Long qw(:config gnu_compat no_bundling no_ignore_case);
use File::Path qw(rmtree);
use File::Spec::Functions qw(catfile);

use FindBin ();
use lib "$FindBin::Bin/lib";
use Dotto::Util;


sub usage () {
    die <<EOF;
    Usage: $0 [OPTIONS]

OPTIONS:
    -h, --help                  show this help.
    -u, --username <user>       specify username.
EOF
}


# chdir parent directory of this script
chdir $FindBin::Bin or die "$FindBin::Bin:$!";

my $needhelp;
my $home;
my $username;
my $config_file;
my $verbose;
GetOptions(
    'h|help'
        => \$needhelp,
    'u|username=s'
        => \$username,
    'c|config-file=s'
        => \$config_file,
    'v|verbose'
        => \$verbose,
) or usage;
usage if $needhelp;


if (defined $username) {
    $home = get_home_from_user $username;
}
else {
    ($username, $home) = determine_user_and_home;
}

if (!defined $config_file && exists $ENV{DOTTORC}) {
    $config_file = $ENV{DOTTORC};
}
my $c = load_config($config_file);

for my $file (map { convert_filename $c, $_ } @{$c->{files}}) {
    my $src  = catfile($home, $file);
    my $dest = catfile($c->{directory}, $file);

    say("$src -> $dest") if $verbose;
    install($src, $dest, $username);
}

for my $f (@{$c->{removed_files}}) {
    if (-e $f) {
        rmtree($f);
    }
}
